class HospitalData {
  // List of major cities in Pakistan
  static const List<String> pakistanCities = [
    'Karachi',
    'Lahore',
    'Islamabad',
    'Faisalabad',
    'Rawalpindi',
    'Multan',
    'Peshawar',
    'Quetta',
    'Sialkot',
    'Gujranwala',
    'Hyderabad',
  ];

  // Mapping of cities to hospitals
  static const Map<String, List<String>> hospitalsByCity = {
    'Karachi': [
      'Aga Khan University Hospital',
      'Jinnah Postgraduate Medical Centre',
      'Liaquat National Hospital',
      'South City Hospital',
      'National Medical Centre',
      'OMI Hospital',
      'Dr. Ziauddin Hospital',
      'Patel Hospital',
      'Indus Hospital',
      'Civil Hospital',
    ],
    'Lahore': [
      'Shaukat Khanum Memorial Cancer Hospital',
      'Doctors Hospital',
      'Sheikh Zayed Hospital',
      'Services Hospital',
      'Mayo Hospital',
      'Lahore General Hospital',
      'Hameed Latif Hospital',
      'Fatima Memorial Hospital',
      'Farooq Hospital',
      'National Hospital',
    ],
    'Islamabad': [
      'Pakistan Institute of Medical Sciences (PIMS)',
      'Shifa International Hospital',
      'Federal Government Services Hospital',
      'Ali Medical Centre',
      'Maroof International Hospital',
      'Kulsum International Hospital',
      'Quaid-e-Azam International Hospital',
      'Holy Family Hospital',
    ],
    'Faisalabad': [
      'Allied Hospital',
      'DHQ Hospital',
      'Faisalabad Institute of Cardiology',
      'National Hospital',
      'Mujahid Hospital',
      'Faisal Hospital',
    ],
    'Rawalpindi': [
      'Combined Military Hospital (CMH)',
      'Holy Family Hospital',
      'Benazir Bhutto Hospital',
      'Rawalpindi General Hospital',
      'Cantonment General Hospital',
      'Hearts International Hospital',
    ],
    'Multan': [
      'Nishtar Hospital',
      'Chaudhry Pervaiz Elahi Institute of Cardiology',
      'Children Complex Hospital',
      'Fatima Jinnah Hospital',
      'Combined Military Hospital Multan',
    ],
    'Peshawar': [
      'Lady Reading Hospital',
      'Khyber Teaching Hospital',
      'Hayatabad Medical Complex',
      'Northwest General Hospital',
      'Rahman Medical Institute',
    ],
    'Quetta': [
      'Civil Hospital',
      'Bolan Medical Complex',
      'Combined Military Hospital Quetta',
      'Akram Hospital',
      'Helper Hospital',
    ],
    'Sialkot': [
      'Allama Iqbal Memorial Hospital',
      'Combined Military Hospital Sialkot',
      'Sialkot Medical Complex',
      'Idrees Teaching Hospital',
    ],
    'Gujranwala': [
      'DHQ Hospital',
      'Combined Military Hospital Gujranwala',
      'Siddique Sadiq Memorial Trust Hospital',
      'City Hospital',
    ],
    'Hyderabad': [
      'Liaquat University Hospital',
      'Isra University Hospital',
      'Red Crescent Hospital',
      'Asian Hospital',
      'Civil Hospital',
    ],
  };
} 